services:
  kintsugi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kintsugi-dam
    ports:
      - "3000:3000" # Frontend UI
      - "8000:8000" # Backend API
    volumes:
      - ./backend/data:/app/backend/data
      - /path/to/user/media:/media:rw
    restart: unless-stopped