"""Initial Revision

Revision ID: 18352b12f428
Revises:
Create Date: 2026-05-05 22:40:57.068106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18352b12f428'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=True),
    sa.Column('last_hashed_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_filepath'), 'media_files', ['filepath'], unique=True)
    op.create_table('plugin_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plugins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('installed_version', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_privileged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('bytes_processed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_webhook_url', sa.String(), nullable=True),
    sa.Column('ntfy_topic_url', sa.String(), nullable=True),
    sa.Column('consensus_threshold', sa.Integer(), nullable=False),
    sa.Column('cloud_credits', sa.Integer(), nullable=False),
    sa.Column('maintenance_start', sa.String(), nullable=False),
    sa.Column('maintenance_end', sa.String(), nullable=False),
    sa.Column('monitored_directory', sa.String(), nullable=False),
    sa.Column('triage_directory', sa.String(), nullable=False),
    sa.Column('scan_intensity', sa.String(), nullable=False),
    sa.Column('is_setup_complete', sa.Boolean(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('auto_restore', sa.Boolean(), nullable=False),
    sa.Column('auto_restore_cloud', sa.Boolean(), nullable=False),
    sa.Column('auto_restore_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_use_kintsugi_cloud', sa.Boolean(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('snapshot_mount_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('license_key', sa.String(), nullable=True),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('paddle_customer_id', sa.String(), nullable=True),
    sa.Column('paddle_subscription_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('scan_history')
    op.drop_table('plugins')
    op.drop_table('plugin_configs')
    op.drop_index(op.f('ix_media_files_filepath'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
