"""add triage engine models

Revision ID: 4f5c885debb4
Revises: de9421286d3c
Create Date: 2026-05-20 13:49:12.041882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5c885debb4'
down_revision: Union[str, Sequence[str], None] = 'de9421286d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('quarantine_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_entries_media_file_id'), 'triage_entries', ['media_file_id'], unique=False)
    op.add_column('system_settings', sa.Column('approved_retention_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'approved_retention_days')
    op.drop_index(op.f('ix_triage_entries_media_file_id'), table_name='triage_entries')
    op.drop_table('triage_entries')
    # ### end Alembic commands ###
