"""Add Profile and FleetNode node_type

Revision ID: 5db0d8a4fc01
Revises: a65d0a0825c1
Create Date: 2026-05-28 12:49:41.524601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db0d8a4fc01'
down_revision: Union[str, Sequence[str], None] = 'a65d0a0825c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('profiles')
    except:
        pass
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=True)
    try:
        op.add_column('fleet_nodes', sa.Column('node_type', sa.String(), nullable=False))
    except:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('fleet_nodes', 'node_type')
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
