"""rename hashed_date to scanned_at

Revision ID: 65738c6acb6d
Revises: 18352b12f428
Create Date: 2026-05-05 23:04:55.834706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65738c6acb6d'
down_revision: Union[str, Sequence[str], None] = '18352b12f428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('last_scanned_at', sa.DateTime(), nullable=True))
    op.drop_column('media_files', 'last_hashed_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('last_hashed_date', sa.DATETIME(), nullable=True))
    op.drop_column('media_files', 'last_scanned_at')
    # ### end Alembic commands ###
