"""add_fleet_models_autogen2

Revision ID: a5e677dd6349
Revises: 4dbc363dce80
Create Date: 2026-05-21 14:22:40.135422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e677dd6349'
down_revision: Union[str, Sequence[str], None] = '5be2e184ce57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('private_key_pem', sa.String(), nullable=False),
    sa.Column('public_cert_pem', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fleet_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('public_key_thumbprint', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fleet_nodes_public_key_thumbprint'), 'fleet_nodes', ['public_key_thumbprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleet_nodes_public_key_thumbprint'), table_name='fleet_nodes')
    op.drop_table('fleet_nodes')
    op.drop_table('fleet_authority')
    # ### end Alembic commands ###
