"""Add is_local_only to FleetNode

Revision ID: a65d0a0825c1
Revises: a5e677dd6349
Create Date: 2026-05-25 21:18:56.616433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65d0a0825c1'
down_revision: Union[str, Sequence[str], None] = 'a5e677dd6349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fleet_nodes', sa.Column('is_local_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fleet_nodes', 'is_local_only')
    # ### end Alembic commands ###
