"""add license_tier to system_settings

Revision ID: ca3af4ab3d31
Revises: de9421286d3c
Create Date: 2026-05-20 13:04:23.267325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3af4ab3d31'
down_revision: Union[str, Sequence[str], None] = 'de9421286d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('license_tier', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'license_tier')
    # ### end Alembic commands ###
