"""replace privileged with permissions json and add enable_3rd_party_plugins

Revision ID: de9421286d3c
Revises: 65738c6acb6d
Create Date: 2026-05-16 01:30:26.114773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9421286d3c'
down_revision: Union[str, Sequence[str], None] = '65738c6acb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('permissions', sa.JSON(), nullable=True))
    op.drop_column('plugins', 'is_privileged')
    op.add_column('system_settings', sa.Column('enable_3rd_party_plugins', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'enable_3rd_party_plugins')
    op.add_column('plugins', sa.Column('is_privileged', sa.BOOLEAN(), nullable=False))
    op.drop_column('plugins', 'permissions')
    # ### end Alembic commands ###
