"use client"

import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { FleetSetupWizard } from "@/components/FleetSetupWizard"
import { WorkerNodeConfig } from "@/components/WorkerNodeConfig"
import { FleetLogViewer } from "@/components/FleetLogViewer"
import { Server, Download, ShieldCheck, Cpu } from "lucide-react"
import JSZip from "jszip"
import { saveAs } from "file-saver"
import { toast } from "sonner"

export default function FleetPage() {
    const [activeTab, setActiveTab] = React.useState<"ingestion" | "compute">("compute");
    const [generating, setGenerating] = React.useState(false);

    const [showWizard, setShowWizard] = React.useState(false);
    const [selectedNodeId, setSelectedNodeId] = React.useState<string | null>(null);


    const generateBundle = async () => {
        setGenerating(true);
        toast.info("Generating cryptographic payload...", { duration: 2000 });

        try {
            const zip = new JSZip();

            // 1. kintsugi-node.conf
            const confContent = `
# Kintsugi-DAM Node Configuration
# Auto-generated by UI Client
NODE_ROLE=${activeTab === "ingestion" ? "INGEST_PROXY" : "WORKER_NODE"}
MASTER_URI=wss://${window.location.hostname}:8443/nexus
VERIFY_SSL=true
MTLS_CERT_PATH=/etc/kintsugi/certs/node.crt
MTLS_KEY_PATH=/etc/kintsugi/certs/node.key
CA_CERT_PATH=/etc/kintsugi/certs/ca.crt
MAX_CONCURRENCY=auto
`.trim();
            zip.file("kintsugi-node.conf", confContent);

            // 2. Mock Cryptographic Assets (Normally fetched from secure API)
            // Using standard placeholder PEMs for the structural requirement
            const caCrt = `-----BEGIN CERTIFICATE-----\nMIIB...[CA_CERT_DATA_MOCK]...==\n-----END CERTIFICATE-----`;
            const nodeCrt = `-----BEGIN CERTIFICATE-----\nMIIB...[NODE_CERT_DATA_MOCK]...==\n-----END CERTIFICATE-----`;
            const nodeKey = `-----BEGIN RSA PRIVATE KEY-----\nMIIE...[NODE_KEY_DATA_MOCK]...==\n-----END RSA PRIVATE KEY-----`;

            zip.file("ca.crt", caCrt);
            zip.file("node.crt", nodeCrt);
            zip.file("node.key", nodeKey);

            // Generate zip blob
            const content = await zip.generateAsync({ type: "blob" });

            // Trigger download
            saveAs(content, `kintsugi-${activeTab}-bundle.zip`);

            toast.success("Enrollment bundle generated successfully!");
        } catch (error) {
            console.error("ZIP Generation failed:", error);
            toast.error("Failed to compile node bundle.");
        } finally {
            setGenerating(false);
        }
    };


    if (showWizard) {
        return <div className="container py-8"><FleetSetupWizard onComplete={() => setShowWizard(false)} /></div>;
    }

    return (
        <div className="max-w-4xl mx-auto space-y-8 py-6">
            <div className="text-center space-y-2 mb-10">
                <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-full mb-2">
                    <Server className="w-8 h-8 text-primary" />
                </div>
                <h1 className="text-3xl font-bold tracking-tight">Fleet Node Enrollment</h1>
                <p className="text-muted-foreground max-w-lg mx-auto">
                    Scale your Kintsugi-DAM architecture by deploying external worker nodes or ingestion proxies across your network.
                </p>
            </div>

            <div className="flex bg-card border border-border p-1 rounded-xl w-full max-w-md mx-auto shadow-sm">
                <button
                    onClick={() => setActiveTab("compute")}
                    className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-sm font-medium rounded-lg transition-all ${activeTab === "compute" ? "bg-primary text-black shadow-md" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}
                >
                    <Cpu className="w-4 h-4" /> Compute Worker
                </button>
                <button
                    onClick={() => setActiveTab("ingestion")}
                    className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-sm font-medium rounded-lg transition-all ${activeTab === "ingestion" ? "bg-primary text-black shadow-md" : "text-muted-foreground hover:text-foreground hover:bg-muted/50"}`}
                >
                    <ShieldCheck className="w-4 h-4" /> Ingestion Proxy
                </button>
            </div>

            <Card className="max-w-2xl mx-auto border-white/10 bg-black/40 backdrop-blur-md">
                <CardHeader className="text-center pb-2">
                    <CardTitle className="text-xl">
                        {activeTab === "compute" ? "Compute Worker Node" : "Ingestion Proxy Node"}
                    </CardTitle>
                    <CardDescription>
                        {activeTab === "compute"
                            ? "Offload heavy image hashing and AI generation tasks to a dedicated bare-metal server."
                            : "Deploy at the edge to scan files before they are written to the main array."}
                    </CardDescription>
                </CardHeader>
                <CardContent className="pt-6">
                    <div className="bg-background/50 border border-border rounded-lg p-4 mb-6 space-y-3">
                        <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Payload Contents</h4>
                        <ul className="text-sm space-y-2 font-mono text-muted-foreground">
                            <li className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span> kintsugi-node.conf</li>
                            <li className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-green-500"></span> ca.crt</li>
                            <li className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-green-500"></span> node.crt</li>
                            <li className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-orange-500"></span> node.key (Keep Secret)</li>
                        </ul>
                    </div>

                    <Button
                        onClick={generateBundle}
                        disabled={generating}
                        className="w-full h-12 text-base font-semibold shadow-[0_0_20px_rgba(var(--primary),0.2)] hover:shadow-[0_0_30px_rgba(var(--primary),0.4)] transition-all"
                    >
                        {generating ? (
                            <div className="flex items-center gap-2">
                                <div className="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin" /> Compiling...
                            </div>
                        ) : (
                            <div className="flex items-center gap-2">
                                <Download className="w-5 h-5" /> Generate Enrollment Bundle
                            </div>
                        )}
                    </Button>
                </CardContent>
            </Card>
        </div>
    )
}
